### ISSUE TITLE
R.invoker signature

### ISSUE THREAD

**Issue by liorshalev01** [donnut/typescript-ramda#102]
`R.invoker` signature take the first parameter as a arity: `Number -> String -> (a -> b -> ... -> n -> Object -> *)` 

However, @types/ramda signature take the first parameter as the function name.

Is this a versioning problem?

Regards,
Lior,

**Comment by jcristovao** [comment]
Yeah, that just seems wrong.
PR welcomed ;)

**Comment by liorshalev01** [comment]
Added PR [https://github.com/donnut/typescript-ramda/pull/106](url)

**Comment by tycho01** [comment]
I've merged this in now. Thank you for fixing this!
