### ISSUE TITLE
error with immutablejs data structures.

### ISSUE THREAD

**Issue by piq9117** [donnut/typescript-ramda#115]
First of all, thank you for `typescript-ramda`.

I'm using `immutablejs` and it gives me this error when I use a List or Map in the second paramater of `filter`
example:
```javascript
const num = List([1, 2, 3, 4, 5]);
const filtered = R.filter(x => x === 5, num);
```
I get this:
`Argument of type 'List<number>' is not assignable to parameter of type 'any[]'.`

So, I went into the types and changed this line 
```javascript
filter<T>(fn: (value: T) => boolean, list: T[]): T[];
```
to
```javascript
filter<T>(fn: (value: T) => boolean, list: Functor<T>): Functor <T>;
```
It worked after I changed it, it also worked on `Map`
example:
```javascript
const numMap = List([Map({
  num1: 1,
  num2: 2,
  num3: 3
})]);
const filteredMap = R.map((x: Map<any, any>) => R.filter(y => y === 1, x), numMap);
```
Is this the right step? what are the repercussions of this modification? Should I submit a PR?

**Comment by tycho01** [comment]
@piq9117 : Generalizing things definitely seems the way to go, and I imagine there might be other functions we might need to update in a similar way.
So currently `map` for functors is returning an array, and I see your point that for these Immutable structures you'd want to get the same thing back.
To my understanding, so far Immutable support in Ramda had largely been relegated to a [separate repo](https://github.com/ramda/ramda/issues/1367). Could you perhaps comment on to what extent there is interop between them currently? Perhaps that'd help answer how many functions would be affected here.

That said, I wonder if `Functor` is the correct abstraction here though. I suppose `Maybe` as a monad would implement the functor interface, but I'm not quite sure filter logically works there (if filter returns `false` on its value, is that `Functor<T>` return value supposed to represent a `Nothing` there or something?).
I'd test using the implementation, but I'd doubt both the implementation and my understanding, hence I'm hoping to discuss here so we could better figure these things out.

**Comment by tycho01** [comment]
On further thought, I wonder if [Iterable](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Iteration_protocols) might be an appropriate abstraction here. There is mention of it in the TS docs [here](https://basarat.gitbooks.io/typescript/content/docs/iterators.html), though I'm having trouble implementing it:
```ts
    interface Iterable {
        // // not worrying about the return type yet, just trying to get the key to work for now: 
        // Symbol.iterator: any;
        // @@iterator: any;
        // [iterator: Symbol]: any;
    }
```

The last attempt gives TS's error stating the key can only be a string or number, implying `Iterable` cannot currently be typed.
Perhaps this is a good question for the TypeScript guys...

**Comment by tycho01** [comment]
I just pushed support for your functor filters as well as a switch to `ArrayLike` for input parameters, which should at least give support for Immutable's `List`. As to its `Map`, I'm under the impression Ramda itself has not really extended support to `Iterable`s in general yet -- for that I fear there isn't much we can type just yet.
Anyway, please try a pull -- I hope I haven't messed too much with your current efforts!
On an `InputArray`, I'm currently wondering if there'd be an immediate use-case for generalizing this part. Nevertheless, if you'd already been doing that, I'm open to the idea. That said, do note I've already sorta tested which parts can use `ArrayLike` (and which can use `Iterable` -- found none).

**Comment by tycho01** [comment]
Open to further suggestions, until then I'll close as all actionable points appear resolved at the moment.

**Comment by piq9117** [comment]
Thank you! yeah. the `Maybe` functor would not work out cuz it's just one specific functor. The functors that the library that doesn't support right now are `List` & `Map` from `immutablejs`. I skimmed through the `Iterable` type, and I think that was also a good solution. On my current situation I just wrap my functors in `R.Functor` pretty much just declaring that it is a functor. However, I would have to wrap every functor in `R.Functor`(i.e `R.Functor<any[]>`, `R.Functor<List<any>>`, `R.Functor<Map<any, any>>`, etc) after the changes that I made. 

Thank you again for the response. I will be communicating any solutions I got.. Thanks!

**Comment by tycho01** [comment]
Yeah, I'm actually a bit surprised I haven't found any issues at Ramda on `Iterable` support.
I'll admit having to manually wrap things in `Functor` feels a bit unfortunate; I'd expect for the interface to work automatically for anything implementing a `map` method. I'd be glad to further improve them / accept PRs if we can get a sense of how to better address your use-case.

**Comment by tycho01** [comment]
Correction: seems they [do](https://github.com/ramda/ramda/issues/1809#issuecomment-256739095) plan on doing iterators.
