### ISSUE TITLE
slice defaults to first returned item with poly

### ISSUE THREAD

**Issue by jon49** [donnut/typescript-ramda#18]
Both of these throw errors in VS 2013 since they default to the previously defined terms.
R.slice(2, 5)(str); //=> 'llo'
R.slice(2)(5, str); //=> 'llo'

Proposed solution:

Create an intermediary `interface` to deal with this problem (something I have done in my own code); which has the varying types in the interface.

I'll update this when I get time to fix it. Possibly with a pull request.

**Comment by donnut** [comment]
solved in d348e96
