### ISSUE TITLE
R.cond API changed from variable arguments to array of pairs

### ISSUE THREAD

**Issue by jon49** [donnut/typescript-ramda#23]
It's not in the docs online but it is reflected in the docs in the latest file.

upgrading to 0.15 is a pain!

**Comment by donnut** [comment]
I'll try to have a look at it tonight. Life would be so much better once the ramda API is frozen ;)

**Comment by donnut** [comment]
New test for `cond` seems to confirm its correctness: 21164bfa6e9a9fde3111c0a96c691ff326d72fad
