### ISSUE TITLE
typings and tsd

### ISSUE THREAD

**Issue by remojansen** [donnut/typescript-ramda#39]
How far are these type definitions from being published to DefinitelyTyped?

Thanks!

**Comment by donnut** [comment]
There is still quite some work to do, especially for the more complex but also less frequently used functions. We could publish it, but I'm not sure if that is a good idea. It's still in a sort of alpha stage.

**Comment by donnut** [comment]
Added extra external type definition in 1f34042ea566d64214d7c01534ad805604e9cff2
This repo is now added to [typings/registry](https://github.com/typings/registry)

**Comment by remojansen** [comment]
Thanks a lot for all the hard work :+1:

**Comment by donnut** [comment]
You're welcome.
