### ISSUE TITLE
Change/Addition of extra type parameters to some functions?

### ISSUE THREAD

**Issue by MikeyBurkman** [donnut/typescript-ramda#56]
I'm primarily referring to R.propEq() in my situation, but this probably applies elsewhere. There are two parts to my question/issue.

First, in propEq, currently the type parameter `<T>` is on the `val` parameter, which I don't personally find very useful. (Maybe I'm missing something.) I think it would be much more useful for `<T>` to be the type of `obj`, as I find that plays better with partial application:

``` ts
// Current definition: propEq<T>(name: string, val: T): (obj: any) => boolean;
let findMatching1 = R.filter(R.propEq('id', 1)); // Return type is any[] -> any[]

// Suggested definition: propEq<T>(name: string, val: any): (obj: T) => boolean;
let findMatching2 = R.filter(R.propEq<User>('id', 1)); // Return type is User[] -> User[]
```

Second: It looks like TS (at least as of 1.8.10) can support having multiple definitions, identical except for their generic types. The following seems to work fine:

``` ts
propEq(name: string, val: any): (obj: any) => boolean;
propEq<T>(name: string, val: any): (obj: T) => boolean;
```

Having both definitions allows you to do either of the examples in my code above, depending on your scenario. 

What do you think? Of course, this is particular situation relies on my belief that the type of `val` is not useful. We could add additional type parameters <T, U> for both `val` and `obj` but we could start to see a sort of exponential explosion of near-identical definitions. (And it does break backwards compatibility, I know.)

**Comment by donnut** [comment]
On the first point, the types of `val` and `obj`, I agree with you completely. Your suggestion makes more sense than the current definition.

I have followed the recent developments of TS that closely, but the support of multiple definitions make a lot of sense. Previously one had to write:
```
propEq(name: string, val: any): {
    (obj: any): boolean;
    <T>(obj: T): boolean;
}
but this is more elegant for sure.

Making typings for ramda is a bit like shooting two rapid moving targets as both typescript and ramda keep adding new stuff. Which is a good thing btw.
