### ISSUE TITLE
R.merge and type intersection

### ISSUE THREAD

**Issue by pzavolinsky** [donnut/typescript-ramda#57]
Hi, I'm having problems with `R.merge(a,b)` where `b` is a subset of `a`:

```typescript
interface Person {
  first: string,
  last: string
};
function setLast(last: string, person: Person) : Person {
  return R.merge(person, { last });
}
```

The code above complains with:
```
error TS2322: Type '<T1>(a: T1) => T1 & { last: string; }' is not assignable to type 'Person'.
  Property 'first' is missing in type '<T1>(a: T1) => T1 & { last: string; }'.
```
If I explicitly state `T1` and `T2`, the code works but it gets very ugly:

```typescript
function setLast(last: string, person: Person) : Person {
  return R.merge<Person, { last:string }>(person, { last });
}
```

Most of the time I use `R.merge` to update existing properties of immutable objects (like *last* in the example above). I think support for this use-case should be straight-forward. Worst case, this might be OKish:

```typescript
R.merge<Person>(person, { last }) : Person & { last:string } // == Person
```

Having to specify the type of `{ last }` feels like an unnecessary pain.

On a side note, for the use-case when I'm augmenting a type (i.e. A & B != A) I have no problem defining the new type.

**Comment by pzavolinsky** [comment]
More info on this.

It looks like the problem is a conflict in these two definitions:

```typescript
merge<T2>(a: R.placeholder, b: T2): <T1>(a: T1) => T1&T2;
merge<T1, T2>(a: T1, b: T2): T1 & T2;
```
Removing the first one fixes the issue. 

I recommend reviewing (and possibly removing) the `R.placeholder` variation in favor simplifying the most common use-case (at least in my experience) of using `R.merge` with one or two objects.

Incidentally, any `R.placeholder` scenario can be replaced with a `R.flip(R.merge)`.

**Comment by donnut** [comment]
I just came up with the same finding after 8 days ;)
[This](http://www.typescriptlang.org/play/index.html#src=interface%20Person%20{%0D%0A%20%20first%3A%20string%2C%0D%0A%20%20last%3A%20string%0D%0A}%0D%0A%0D%0Alet%20R%3A%20R.Static%0D%0A%0D%0Adeclare%20module%20R%20{%0D%0A%09interface%20Static%20{%0D%0A%09%09merge%3CT1%2CT2%3E%28a%3AT1%2C%20b%3AT2%29%3A%20T1%26T2%0D%0A%09}%0D%0A}%0D%0A%0D%0A%0D%0Aconst%20a%3A%20Person%20%3D%20{first%3A%20%27Joe%27%2C%20last%3A%20%27Foo%27}%0D%0Aconst%20b%20%3D%20%27Doe%27%0D%0A%0D%0AR.merge%20%3D%20%28a%2C%20b%29%20%3D%3E%20{%0D%0A%09let%20c%20%3D%20{}%0D%0A%09for%20%28let%20i%20in%20a%29%20c[i]%20%3D%20a[i]%0D%0A%09for%20%28let%20i%20in%20b%29%20c[i]%20%3D%20b[i]%0D%0A%09return%20c%3B%0D%0A}%0D%0A%0D%0A%0D%0Afunction%20setLast%28last%3A%20string%2C%20person%3A%20Person%29%20%3A%20Person%20{%0D%0A%20%20return%20R.merge%28person%2C%20{%20last%20}%29%3B%0D%0A}%0D%0A%0D%0A%0D%0A) works indeed.

The placeholder thing is something I'm not happy with at all. It doesn't fit typescript well, although I do see its use-case. It is probably better to make a clear choice and just not support them at all.

**Comment by pzavolinsky** [comment]
> The placeholder thing is something I'm not happy with at all. (...) It is probably better to make a clear choice and just not support them at all.

Agreed, we decided not to use `R.__` at all in our codebase (since it felt more obscure than the `R.flip` alternative).

**Comment by donnut** [comment]
I'll shoot a PR with the placeholders removed. If there are no serious objections, we remove them definitely.

**Comment by pzavolinsky** [comment]
Cool @donnut , thanks!
