### ISSUE TITLE
addIndex doesn't play with reduce

### ISSUE THREAD

**Issue by jcristovao** [donnut/typescript-ramda#62]
Hey,
So, since [ramda 0.15](https://github.com/ramda/ramda/issues/1186) the overall consensus is that indexed functions are removed from ramda, and instead we do R.addIndex(functionToAddIndex).

Unfortunately, this does not play with reduce to generate the [reduceIndexed]() function:

```
var reduceIndexed = R.addIndex(R.reduce);
```

Yields:
```
TS2345: Argument of type '{ <T, TResult>(fn: (acc: TResult, elem: T) => TResult | Reduced<TResult>, acc: TResult, list: T[]...' is not assignable to parameter of type '(f: (item: any) => any (...)

```

I added this as a quick fix, but I'm pretty sure there might be a more accurate definition:

```typescript
addIndex<T, U>(fn: (f: (item: T) => U, list: T[]) => U[])
              : CurriedFunction2<(item: T, idx: number, list?: T[]) => U, T[], U[]>;
// I've added this
addIndex<T, U>(fn: (f: (acc:U, item: T) => U, aci, list: T[]) => U[])
              : CurriedFunction3<(acc, item: T, idx: number, list?: T[]) => U, U, T[], U[]>;
```

What do you think?

**Comment by donnut** [comment]
Good that you mention this one. It was still on my todo list. I've quickly tried your suggestion and it seems to work (I added type for aci too)
However, something goes wrong with overload the addIndex function, so now other tests fail that used to pass with the sole `addIndex` definition.
