### ISSUE TITLE
Type definition for evolve breaks nested evolution.

### ISSUE THREAD

**Issue by brianbondlink** [donnut/typescript-ramda#65]
The example given in the Ramda documentation illustrates using evolve to modify attributes several degrees deep into a nested structure.

This is no longer possible with the latest type defintion for evolve, since it expects a {[index: string]: function}

I realize it may not have been as well typed, but this worked on a previous version of the type definitions.

**Comment by donnut** [comment]
Can you check if the [definition](https://github.com/donnut/typescript-ramda/blob/2f9464ee7eb6ff242a4a111943fb885dee6cede4/ramda.d.ts) works for you?

**Comment by brianbondlink** [comment]
@donnut yes that is the definition we had prior to updating the definition which worked fine for nested evolutions.

**Comment by donnut** [comment]
I created an [alternative typing](https://github.com/donnut/typescript-ramda/tree/evolve). Can you check if this works for you? And maybe share the snipped you encountered problems with?

**Comment by donnut** [comment]
@brianbondlink do you have a snippet to share :wink:

**Comment by brianbondlink** [comment]
Sorry @donnut missed your last reply. I haven't gotten to test the typing yet, but for a snippet take a look at the ramda docs for evolve. It demonstrates the nested evolution that was broken initially

**Comment by donnut** [comment]
Ok, thanks. The ramda doc example is fixed with this modification.

**Comment by brianbondlink** [comment]
Excellent thank you

**Comment by donnut** [comment]
I'll update the code this weekend. Thanks for reporting the issue :+1:

**Comment by donnut** [comment]
@brianbondlink 
done in bc6c44a281b3fc44633a61591e11943e7c042582

**Comment by brianbondlink** [comment]
Thanks!

**Comment by donnut** [comment]
The test of evolve fails after all (not in the atom-editor?). Has to do with [index: string] key.

**Comment by jcristovao** [comment]
I am also having problems with the definition currently on master.
To me this:

```
     interface xpto  { a: number, b: number };
     var test : xpto = { a: 1, b: 2};
     const a3 : xpto = R.evolve({ a: R.add(1)}, test );
```

Is totally valid code, that typescript rejects with:

```
TS2322: Type 'Nested<xpto>' is not assignable to type 'xpto'.Property 'a' is missing in type 'Nested<xpto>'. [typescript/tsc]
```

With the alternative it works:
```
evolve(transformations: {[index: string]: (value: any) => any}, obj: any): any;
evolve(transformations: {[index: string]: (value: any) => any}): (obj: any) => any;
```

**Comment by tycho01** [comment]
Right now, both versions of the typing are in, meaning all tests are passing. However, that doesn't mean this is resolved yet; our currently having to resort to `any` typings here shows that there is room for improvement in our inference.
