### ISSUE TITLE
isEmpty should accept objects

### ISSUE THREAD

**Issue by jcristovao** [donnut/typescript-ramda#66]
Hi!
Shouldn't `isEmpty`be more polymorphic?

http://ramdajs.com/0.21.0/docs/#isEmpty

Is should accept at least objects (to test for emptyness), and hence I'm questioning if should not just be:

```typescript
isEmpty(value: any): boolean; 
```

**Comment by donnut** [comment]
I agree. It is too strict like this and your suggestion solves that. PR?
