### ISSUE TITLE
better typing for toPairs, tentative.

### ISSUE THREAD

**Issue by nahuel** [donnut/typescript-ramda#71]
`toPairs` is currently defined as:

``` ts
toPairs<F,S>(obj: {[k: string]: S} | {[k: number]: S} | any): [F,S][];
```

this results in the following inference:

``` ts
const a1 = R.toPairs({1:true})                    // type inferred: [{}, {}][]
const a2 = R.toPairs({"1":true})                  // type inferred: [{}, {}][]
const a3 = R.toPairs<string,boolean>({"1":true})  // type inferred: [string, boolean][]
```

If you change the `toPairs` signature to:

``` ts
toPairs<V>(obj : {[k : string] : V}) : [string,V][];
```

then the types inferred will be:

``` ts
const b1 = R.toPairs({1:true})             // type inferred: [string, boolean][]
const b2 = R.toPairs({"1":true})           // type inferred: [string, boolean][]
const b3 = R.toPairs<boolean>({"1":true})  // type inferred: [string, boolean][]
```

I don't know if this new signature is really valid, because:
1. Why is the `any` type included in the original signature? Using something non-object like with `toPairs` seems like an error you want to trap at compile time.
2. Why is `{[k:number] : S}` included in the original signature? Given in javascript keys are always converted to strings. Note the original `toPairs` always returns keys as `string`'s, including the case when the argument is an array.

**Comment by tycho01** [comment]
This has been incorporated now. Thank you for suggesting this! :)
