### ISSUE TITLE
Obscure definition problem

### ISSUE THREAD

**Issue by ivan-kleshnin** [donnut/typescript-ramda#73]
This code is ok, but does not compile

``` ts
let filterMatrix = function (v: number, m: Array<Array<number>>): Array<number> {
  return chain(filter((c) => c == v), m)
}

let b = [
  [0, 1],
  [1, 0]
]

console.log(filterMatrix(1, b)) // --> [1, 1]
```

I'm getting this

```
TSError: ⨯ Unable to compile TypeScript
src/board.ts (11,10): Type '{}[]' is not assignable to type 'number[]'.
  Type '{}' is not assignable to type 'number'.
```

**Comment by ivan-kleshnin** [comment]
Error disappears if no currying is present.

```ts
let filterByState = function (state: number, board: Board): Array<Card> {
  return chain((r) => filter((c) => c[0] == state, r), board)
}
```

**Comment by tycho01** [comment]
Your hunch was right: the curried `filter` definition had an issue. Just now it used `filter<T>(pred: Pred<T>): <T>(list: List<T>) => T[];`, which should have been `filter<T>(pred: Pred<T>): (list: List<T>) => T[];`.

Note that in the former version the generic was redefined halfway through (no longer the same `T`!), as a result of which the type variables failed to link up.
Having fixed that, your example type-checks presuming you allow it to find the parameter type for `(c) => c == v`, using `(c: number) => c == v` or `R.equals(v)`.

This helped me track down a bunch of related cases of duplicate generics as well. Thank you for reporting this! In fact, this is making me reconsider the 'solution' to #90...

**Comment by ivan-kleshnin** [comment]
@tycho01 thanks for taking time to fix this!

**Comment by tycho01** [comment]
You're welcome; thank you for your helpful bug reports. :)
