### ISSUE TITLE
Map definition is overly restrictive.

### ISSUE THREAD

**Issue by jcristovao** [donnut/typescript-ramda#77]
```
R.map(parseInt,{a:'1',b:'2'});
```

Is not accepted.
Are we supposed to declare a Functor for each object we intend to map over?
This is clearly not practical at all.

Preferable to have:

```
map<T, U>(fn: (x: T) => U, obj: any): any;
```

What do you think?

**Comment by donnut** [comment]
You could do that, but the returned value 'breaks' the definition chain as it always returns `any`.

**Comment by jcristovao** [comment]
Perhaps a stupid question, I am a bit tired today, but could `map<T, U, V>(fn: (x: T) => U, obj: V): V;  ` do the trick then?

**Comment by davidspiess** [comment]
Same problem, any ideas how to solve this?

**Comment by tycho01** [comment]
Perhaps `map<T, U, V>(fn: (x: T) => U, obj: { [k: string]: T }): { [k: string]: U };`?

**Comment by tycho01** [comment]
I've included this now. There is still room for improvement, but I think much of it is dependent on further progress in TypeScript itself. If you know other ways we could improve this, feel free to let us know!
