### ISSUE TITLE
[RFC] number typing for prop(), propEq() and friends

### ISSUE THREAD

**Issue by nateabele** [donnut/typescript-ramda#82]
Hey, I noticed you had a few entries like this:

```javascript
        // propEq<T>(name: number, val: T, obj: any): boolean;
        propEq<T>(name: string, val: T): (obj: any) => boolean;
        // propEq<T>(name: number, val: T): (obj: any) => boolean;
```

I use `prop()` and `propEq()` for array offsets pretty frequently, so I locally patched them to add `number` support. Obviously that's not ideal, so I'd be happy to push you a PR if you're interested.

Thanks for investing the time to maintain this.

**Comment by donnut** [comment]
I'm happy to receive a PR!

**Comment by donnut** [comment]
PR #83  probably solves your issue

**Comment by nateabele** [comment]
Thanks! I'll take a crack at it and see how it goes.
