### ISSUE TITLE
Errors on curried R.match 

### ISSUE THREAD

**Issue by whitecolor** [donnut/typescript-ramda#85]
![image](https://cloud.githubusercontent.com/assets/736697/18026771/d0f39d34-6c6a-11e6-9d29-3231c738b95c.png)
I believe need to add signature

```
/**
         * Tests a regular expression agains a String
         */
        match(regexp: RegExp, str: string): any[];
        match(regexp: RegExp): (str: string) => any[];
```

**Comment by whitecolor** [comment]
Aso mybe to consider more concrete interface for result instead of `any`? something like:
`string[] & {index: number, input: string}`

**Comment by whitecolor** [comment]
Seem to be fixed but not published, but also consider my second proposal about return type `string[] & {index: number, input: string}`

**Comment by donnut** [comment]
Can you check if #87 works for you?
I'm not sure why you want to add `{index: number, input: string}` to the returned array or strings.
I haven't worked with Symbols much so I can't answer that question. Needs to dig into that topic for sure.

**Comment by whitecolor** [comment]
{index: number, input: string} - see the result of `str.match` operation

**Comment by whitecolor** [comment]
```
> "something".match(/something/)
[ 'something', index: 0, input: 'something' ]
>
```

**Comment by donnut** [comment]
The API of `ramda`, which is the lead for `typescript-ramda`, only returns `string[]`. If you want to add the additional data from `str.match` you better start a issue on `ramda/ramda`
