### ISSUE TITLE
where typing

### ISSUE THREAD

**Issue by donnut** [donnut/typescript-ramda#9]
@jon49 Following up on PR #7, I came up with the following possible solution:
```javascript
interface ObjPred2 {
        [index:string]: (x: any, y: any) => boolean;
}
where<ObjPred2,U>(spec: ObjPred2, testObj: U): boolean;
```
It seems to pass the test, but I haven't poked around to see if it is general enough. What do you think?

**Comment by jon49** [comment]
That seems to work. It would give the user a pointer in the right direction. Although, from playing around with it it doesn't offer the type safety.

```ts
interface Pred2<T> {
    (x: any, y: T): boolean
}
interface ObjPred2<T> {
    [index: string]: Pred2<T>;
}
where<T>(spec: ObjPred2<T>, testObj: T): boolean;

// Tests

var spec2: R.ObjPred2<{x: number; y: number}> =  {x: function(val, obj): boolean { return  val + obj.y > 10; }};
R.where(spec2, {x: 2, y: 7}); //=> false
R.where(spec2, {x: 3, y: 8}); //=> true
R.where({x: (val, obj) => val + obj.y > 10}, {x: 3, y: 8})
```

The above seems to make it more type safe and to fail when `obj` doesn't use correct properties. Still not working for making `x` into other property names though. But it is much better than before!
