### ISSUE TITLE
path/prop: also allow number (esp. for navigating arrays)?

### ISSUE THREAD

**Issue by tycho01** [donnut/typescript-ramda#94]
Currently, Ramda's `path` / `prop` and similar methods are described in their docs as using string paths/props, while in its implementation -- and imho reasonably so esp. when dealing with Arrays -- also allows numbers:

```
R.path([0, 'a'], [{ a: 1 }])
// 1
R.path(['0', 'a'], [{ a: 1 }])
// 1
R.prop(0, ['a'])
// "a"
R.prop(0, { '0': 'a' })
// "a"
```

Now, I would like for the typings to also allow me to use these functions how I was already using them. You may counter this would clash with Ramda's docs, and therefore possibly intention. So I guess the question here is, would you consider this a bug in Ramda's implementation, or should we request they adjust their docs and accordingly allow this in the typings?

**Comment by tycho01** [comment]
Note that `toPairs` does use `{[k: string]: S} | {[k: number]: S}`. I'm thinking we could have a `type Prop = string | number;`, a `type Path = Prop[];`, then have `toPairs` use `{[k: Prop]: S}` to abstract that part.

**Comment by jcristovao** [comment]
I would say that it's probably Ramda's docs which are outdated, but perhaps you should ask there ;)

Nevertheless, a PR is most welcomed, you seem to be heading in the right direction
