### ISSUE TITLE
publish on npm?

### ISSUE THREAD

**Issue by whitecolor** [donnut/typescript-ramda#96]
Are you going to publish it on npm as `@types/ramda`?

**Comment by jonaskello** [comment]
I don't think you can directly publish there. Seems like all the npm packages on @types are automatically exported from DefinitelyTyped, but from a special branch there called types-2.0. Not sure how you could put the typings there. Maybe make a PR to that branch on dt?

**Comment by jonaskello** [comment]
[Here](https://github.com/Microsoft/types-publisher) is the source for the tool that publishes from DefinitelyTyped to @types on npm. Still not sure how to contribute typings though. The [guidelines](http://definitelytyped.org/guides/contributing.html) does not mention how to actually get the typings into @types on npm. The [blogpost](https://blogs.msdn.microsoft.com/typescript/2016/06/15/the-future-of-declaration-files/) does not mention that either. Anyone else have a clue how to contribute typings to @types? Would be really nice to get the ramda typings in there.

**Comment by MikeyBurkman** [comment]
It looks like it was indeed published to NPM about the same time you asked this lol.

https://www.npmjs.com/package/@types/ramda

**Comment by donnut** [comment]
Closing issue as the typing are available on npm now
