### ISSUE TITLE
Installing as a global module fails

### ISSUE THREAD

**Issue by ravishivt** [donnut/typescript-ramda#97]
I get the following error when trying to install with the global option as per the README.  I also tried `dt~ramda` and it gave the same error.  I found that #50 changed the typings to an external module format.  Do we need to do something different to support both external module format and global?

```
$ typings install ramda --save --global

typings ERR! message Attempted to compile "ramda" as a global module, but it looks like an external module. You'll need to remove the global option to continue.

typings ERR! cwd <path>
typings ERR! system Darwin 15.6.0
typings ERR! command "/usr/local/bin/node" "/usr/local/bin/typings" "install" "dt~ramda" "--save" "--global"
typings ERR! node -v v5.10.1
typings ERR! typings -v 1.3.3
```

**Comment by donnut** [comment]
As the movement of installing typings is towards npm (https://www.npmjs.com/package/@types/ramda) would this work for you? To reduce maintenance effort I would like to support one package management solution in the future.

**Comment by tycho01** [comment]
I'm going to consider this issue stale for a lack of further response. I hope [this](https://github.com/ramda/ramda/issues/1617) might help address the original concern.
